config/routes.rb
VoluntariandoMe::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  match "/neighborhoods/list(.:format)" => "neighborhoods#list", :as => :list_neighborhoods
  resources :home
  resources :needs
  resources :events do
    member do
      post :join
      delete :leave
      get :participants
    end
  end
  root :to => 'home#index'
end

app/models/event.rb
class Event < ActiveRecord::Base

  belongs_to :owner, :class_name => "User"
  has_many :joins, :class_name => "Event::Join"
  has_many :participants, :through => :joins, :source => :user
  belongs_to :neighborhood
  has_many :needs

  accepts_nested_attributes_for :needs, :allow_destroy => true

  mount_uploader :cover, CoverUploader

  attr_accessible :description, :end_date, :name, :date, :hour, :owner_id, :cover, :neighborhood_id, :needs_attributes

  def participants_by_join_date
    participants.order("event_joins.created_at DESC")
  end

  def has_user?(user_id)
    self.joins.collect(&:user_id).include?(user_id)
  end 

  def self.by_localization(localization_id)
    localization_id ||= 4
    if localization_id.to_i != 4
      joins(:neighborhood).where(["neighborhoods.localization_id = ?", localization_id])
    else
       unscoped
    end
  end
end

app/models/event/join.rb
class Event::Join < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
  attr_accessible :event_id, :user_id
end

app/models/need.rb
class Need < ActiveRecord::Base
  belongs_to :event
  attr_accessible :name, :quantity
end

app/models/neighborhood.rb
class Neighborhood < ActiveRecord::Base
  attr_accessible :localization_id, :name
  has_many :users

  LOCALIZATIONS = [
    "Centro",
    "Zona Sul",
    "Zona Norte",
    "Zona Oeste"
  ]

  def localization
    LOCALIZATIONS[self.localization_id]
  end
end

app/models/profession.rb
class Profession < ActiveRecord::Base
  attr_accessible :name
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  
  has_many :own_events, :foreign_key => "owner_id", :class_name => "Event"
  has_many :joins, :class_name => "Event::Join"
  has_many :events, :through => :joins

  belongs_to :neighborhood
  belongs_to :profession

  mount_uploader :avatar, AvatarUploader

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :provider, :uid, :name, :admin, :current_password, :neighborhood_id

  validates_presence_of :name, :neighborhood_id, :on => :update
  
  # attr_accessible :title, :body
  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    logger.info "\n\n\n FACEBOOK: #{auth.info}\n\n\n"
    unless user
      user = User.create(
                          name: auth.info.name,
                          provider: auth.provider,
                          uid: auth.uid,
                          email: auth.info.email,
                          password: Devise.friendly_token[0,20]
                        )
    end
    user
  end

  def update_with_password(params={}) 
    if params[:password].blank? 
      params.delete(:password) 
      params.delete(:password_confirmation) if params[:password_confirmation].blank? 
    end 
    update_attributes(params) 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  inherit_resources
  include EventsHelper
  before_filter :is_logged?, :except => [:index, :show, :participants]
  before_filter :is_admin?, :only => [:new, :create, :edit, :update, :destroy]

  def index
    @events = Event.by_localization(params[:localization_id]).page(params[:page]).per(10)
  end

  def create
    params[:event].merge!(:owner_id => current_user.id)
    create!
  end

  def join
    @join = Event::Join.new(:event_id => params[:id], :user_id => current_user.id)
    @event = @join.event
    if @join.save
      message = t("events.join_success")
    else
      message = t("events.join_error")
    end
    render :json => {:html => toggle_join_event, :message => message}
  end

  def leave
    @join = current_user.joins.find_by_event_id(params[:id])
    @event = @join.event
    if @join.try(:destroy)
      message = t("events.leave_success")
    else
      message = t("events.leave_error")
    end
    render :json => {:html => toggle_join_event, :message => message}
  end

  def participants
    event = Event.find(params[:id])
    participants = event.participants_by_join_date
    response = {:modal_header => t('events.participants'), :modal_body => "<ul>"}
    participants.each do |participant|
      response[:modal_body] << "<li>#{participant.email}</li>"
    end
    response[:modal_body] << "</ul>"
    render :json => response
  end

  protected
    def is_logged?
      unless current_user
        flash[:error] = t('view_errors.not_logged')
        redirect_to root_path
      end
    end
    
    def is_admin?
      unless current_user.admin?
        flash[:error] = t('view_errors.not_admin')
        redirect_to root_path
      end
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/needs_controller.rb
class NeedsController < ApplicationController
  def new
    render :partial => "new", :locals => {:need => Need.new}
  end
end

app/controllers/neighborhoods_controller.rb
class NeighborhoodsController < ApplicationController

  def list
    @neighborhoods = Neighborhood.find_all_by_localization_id(params[:localization_id])
    render :json => @neighborhoods.collect {|n| {:name => n.name, :value => n.id} }
  end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)
    

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def facebook_app_id
    "347600791981595"
  end

  # def facebook_url
  #   "https://www.facebook.com/dialog/feed"
  # end

  # def caption
  #   "Voluntariando.Me"
  # end

  # def url_share
  #   "#{request.host_with_port}/#{url_for}"
  # end

  # def url_button(options)
  #   "#{facebook_url}?
  #   app_id=#{app_id}&
  #   link=#{url_share}&
  #   caption=#{caption}&
  #   redirect_uri=#{url_share}
  #   #{options}"
  # end

  # def share_button(options)
  #   link_to t('facebook_share'), url_button(options)
  # end

  # def share_event_button(event)
  #   share_button("name=#{event.name}&description=#{event.description}&picture=#{event.cover.url(:thumb)}")
  # end

end

app/helpers/events_helper.rb
module EventsHelper
  
  def toggle_join_event(event = nil)
    @event ||= event
    if @event.has_user?(current_user.id)
      button = "<a href='#' onclick='eventToggle(\"#{leave_event_path(@event)}\", \"delete\")\'> #{t('events.leave')}</a>"
    else
      button = "<a href='#' onclick=\'eventToggle(\"#{join_event_path(@event)}\", \"post\")\'> #{t('events.join')}</a>"
    end
    button.html_safe
  end  

  def model_class
    Event
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/needs_helper.rb
module NeedsHelper
end

app/helpers/neighborhoods_helper.rb
module NeighborhoodsHelper
end

app/views/events/_form.html.erb
<%= simple_form_for @event, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :cover, :as => :file %>
  <%= f.input :date, :as => :string, :input_html => { :class => 'date', :value => "#{l(f.object.date) if f.object.date}" } %>
  <%= f.input :hour, :as => :string, :input_html => { :class => 'masked', "data-mask" => "99:99", :value => "#{l(f.object.hour) if f.object.hour}" } %>
  <%= render :partial => 'neighborhoods/list', :locals => { :f => f } %>
  <% if ENV["RAILS_ENV"] == "development" %>
    <fieldset>
      <legend><%= Need.model_name.human.pluralize %></legend>
      <table>
        <th><%= Need.human_attribute_name(:name) %></th>
        <th><%= Need.human_attribute_name(:quantity) %></th>
        <th><%= t('actions') %></th>
        <tbody id="needs">
          <% @event.needs.each do |need| %>
            <%= render :partial => "needs/new", :locals => { :need => need } %>
          <% end %>
          <%= render :partial => "needs/new", :locals => { :need => Need.new } if @event.needs.empty? %>
        </tbody>
      </table>

      <%= link_to_function "Mais necessidades", "moreNeed('#{new_need_path}')" %>
    </fieldset>
  <% end %>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                events_path, :class => 'btn' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/index.html.erb
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
  <%= select_tag :localization, 
      options_for_select( [["Todos", 4]].concat(Neighborhood::LOCALIZATIONS.collect { |localization| [ localization, Neighborhood::LOCALIZATIONS.index(localization) ] }), 
      :selected => params[:localization_id] || 4),
      :id => "filter_localization",  "data-url" => events_path%> 
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:neighborhood_id) %></th>
      <th><%= model_class.human_attribute_name(:date) %></th>
      <th><%= model_class.human_attribute_name(:hour) %></th>
      <% if current_user %>
        <th><%=t '.actions', :default => t("actions") %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to event.name, event_path(event) %></td>
        <td><%= event.description %></td>
        <td><%= event.neighborhood.try(:name) %></td>
        <td><%= I18n.l event.date %></td>
        <td><%= I18n.l event.hour %></td>
        <% if current_user %>
          <td>
            <% if event.owner_id == current_user.try(:id) %>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
                          edit_event_path(event), :class => 'btn btn-mini' %>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                          event_path(event),
                          :method => :delete,
                          :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                          :class => 'btn btn-mini btn-danger' %>
            <% end %>
            <span id="join_buttons" >
              <%= toggle_join_event(event) %>
            </span>
          </td>
        <% end %> 
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @events, :theme => 'twitter-bootstrap' %>
<% if current_user && current_user.admin? %>
  <%= link_to t('.new', :default => t("helpers.links.new")),
              new_event_path,
              :class => 'btn btn-primary' %>
<% end %>

app/views/events/new.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/show.html.erb
<% content_for :facebook_title do %>
  <%= @event.name %>
<% end %>
<% content_for :facebook_description do %>
  <%= @event.description %>
<% end %>
<% content_for :facebook_image do %>
  <%= "http://#{request.host_with_port}#{@event.cover.url(:facebook)}" %>
<% end %>

<%- model_class = Event -%>
<div class="page-header">
  <h1><%= @event.name %></h1>
</div>

<dl class="dl-horizontal">
  <dd><%= image_tag @event.cover.url(:thumb) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @event.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @event.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:neighborhood) %>:</strong></dt>
  <dd><%= @event.neighborhood.try(:name) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:date) %>:</strong></dt>
  <dd><%= I18n.l @event.date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:hour) %>:</strong></dt>
  <dd><%= I18n.l @event.hour %></dd>
</dl>

<div class="form-actions">
  <% if current_user %>
    <span id="join_buttons" >
      <%= toggle_join_event %>
    </span>
  <% end %>
  <%= link_to t('.back', :default => t("helpers.links.back")),
              events_path, :class => 'btn'  %>
  <% if @event.owner_id == current_user.try(:id) %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_event_path(@event), :class => 'btn' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              event_path(@event),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
  <% end %>
  <%= link_to t('share_on_facebook'), "#", :onclick => "postToFeed();" %>
  <%= link_to t('events.show_participants'), "#modal", :class => "btn modal_ajax_button", "data-url" => participants_event_path(@event) %>
</div>

app/views/home/index.html.erb
<%= t('welcome.message') %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" id="viewport">
    <meta property="fb:app_id" content="<%=facebook_app_id%>" id="facebook_app_id"/> 
    <meta property="og:type" content="activity" id="facebook_type"/> 
    <meta property="og:title" content="<%=yield :facebook_title%>" id="facebook_title" /> 
    <meta property="og:image" content="<%=yield :facebook_image%>" id="facebook_image"/> 
    <meta property="og:description" content="<%=yield :facebook_description%>" id="facebook_description"/> 
    <meta property="og:url" content="http://<%=request.host_with_port%><%=url_for%>" id="facebook_url">
    <title><%= content_for?(:title) ? yield(:title) : "VoluntariandoMe" %></title>
    <script src='http://connect.facebook.net/pt_BR/all.js'></script>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%# favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%# favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%# favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%# favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%#favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>
    <%= render :partial => 'shared/top_bar' %>
    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span9">
              <div id="message">
                <%= flash[:error] || flash[:message] %>
              </div>
              <%= yield %>
            </div>
            <div class="span3">
              <div class="well sidebar-nav">
                <h3>Sidebar</h3>
                <ul class="nav nav-list">
                  <li class="nav-header">Sidebar</li>
                  <li><%= link_to "Link1", "/path1"  %></li>
                  <li><%= link_to "Link2", "/path2"  %></li>
                  <li><%= link_to "Link3", "/path3"  %></li>
                </ul>
              </div><!--/.well -->
            </div><!--/span-->
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->
    <%= render :partial => "shared/modal" %>

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/needs/_new.html.erb
<tr id="need">
    <td>
      <%= text_field_tag "event[needs_attributes][][name]", need.name %>
    </td>
    <td>
      <%= text_field_tag "event[needs_attributes][][quantity]", need.quantity, :class => "input_number" %>
    </td>
    <td>
      <%= link_to_function t('remove'), "removeNeed(this, '#{new_need_path}')", :class => "btn btn-mini btn-danger" %>
    </td>
    <%= hidden_field_tag "event[needs_attributes][][id]", need.id %>
    <%= hidden_field_tag "event[needs_attributes][][_destroy]", false, :class => "destroy_field" %>
</td>

app/views/neighborhoods/_list.html.erb
<% content_for :javascripts do %>
  <%= javascript_include_tag :neighborhoods %>
<% end %>
<div class="control-group select optional">
  <%= label_tag :localization, t('localization'), :class => "control-label select optional" %>
  <div class="controls">
    <%= select_tag :neig, 
      options_for_select( Neighborhood::LOCALIZATIONS.collect { |localization| [ localization, Neighborhood::LOCALIZATIONS.index(localization) ] }, 
        :selected => f.object.neighborhood.try(:localization_id)),
      :id => "select_localization",  "data-url" => list_neighborhoods_path, :class => "select"%> 
    </div>
</div>
<%= f.input :neighborhood_id, :collection => Neighborhood.all, :input_html => { :id => :select_neighborhood } %>

app/views/shared/_login_bar.html.erb
<% if current_user %>
  <li><%= link_to t('sign_out'), destroy_session_path(current_user), :method => :delete %></li>
<% else %>
  <li><%= link_to t('sign_in'), new_session_path(:user) %></li>
  <li><%= link_to t('sign_up'), new_registration_path(:user) %></li>
  <li><%= link_to t('sign_in_with_facebook'), omniauth_authorize_path(:user, :facebook) %></li>
<% end %>

app/views/shared/_modal.html.erb
<div class="modal hide" id="modal" style="top: 60%">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h3 id="modal_header"><%= yield :modal_header %></h3>
  </div>
  <div class="modal-body" id="modal_body">
    <%= yield :modal_body %>
  </div>
  <div class="modal-footer" id="modal_footer">
    <!-- <a href="#" class="btn" data-dismiss="modal">Close</a> -->
    <%= yield :modal_footer %>
    <!-- <a href="#" class="btn btn-primary">Save changes</a> -->
  </div>
</div>

app/views/shared/_top_bar.html.erb
 <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "Voluntariando.Me", root_path, :class => "brand" %>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to Event.model_name.human.pluralize, events_path %></li>
              <%= render :partial => "shared/login_bar" %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>